import PreviewSurveys from "pages/Admin/Surveys/ManageSurveys/QuestionSetup/PreviewQuestionsteup";
import adminRouteMap from "./adminRouteMap";
import CreateMyColor from "pages/Admin/DefaultSettings/CreateMyColor/index.page";
import {
  AdminDashboard,
  DepartmentManagement,
  CompanyManagement,
  ParticipantManagement,
  SurveyAnalysis,
  Resources,
  ListofQuestions,
  ViewCrosswalk,
  MyReports,
  CreateSurvey,
  CreateTemplate,
  SavedReports,
  RandomResponse,
  ComparsionCharts,
  ManageDataset,
  ReportGenerator,
  AssignSend,
  ScheduleLog,
  AccountInformation,
  ParticipantProgress,
  ManageSurveys,
  Profile,
  MyUsage,
  ReviewAndEdit,
  AuditTrail,
  DemographicTrendAnalysis,
  Charting,
  ComparativeAnalysis,
  ReviewEditDataset,
  AdminManagement,
  DefaultSettings,
  ComparativeAnalysisDataHarmonization,
  CreateDataset,
  CheckUnauthorized,
  SaveResource,
  AssessmentResponse,
  RBOEQResponse,
  SingleChartReport,
  SummaryChartReport,
  DetailedChartReport,
  IgChartReport,
  DynamicChartReport,
  EmailFilter, 
  PreviewQue
  
} from "../../pages";

export default function route() {
  return [
    {
      path: adminRouteMap?.PREVIEWQUESTIONS?.path,
      name: "preview-questions",
      private: false,
      element: <PreviewQue />,
    },
    {
      path: adminRouteMap?.DASHBOARD?.path,
      name: "Dashboard",
      private: true,
      element: <AdminDashboard />,
    },
    {
      path: adminRouteMap?.DEPARTMENTMANAGEMENT?.path,
      name: "Department Management",
      private: true,
      element: <DepartmentManagement />,
    },
    {
      path: adminRouteMap?.PARTICIPANTMANAGEMENT?.path,
      name: "Participant Management",
      private: true,
      element: <ParticipantManagement />,
    },
    {
      path: adminRouteMap?.COMPANYMANAGEMENT?.path,
      name: "Company Management",
      private: true,
      element: <CompanyManagement />,
    },
    {
      path: adminRouteMap?.RESOURCES?.path,
      name: "Resources",
      private: true,
      element: <Resources />,
    },
    {
      path: adminRouteMap?.VIEWCROSSWALK?.path,
      name: "View Crosswalk",
      private: true,
      element: <ViewCrosswalk />,
    },
    {
      path: adminRouteMap?.CREATESURVEY?.path,
      name: "Create-survey",
      private: true,
      element: <CreateSurvey />,
    },
    {
      path: adminRouteMap?.MANAGESURVEYS?.path,
      name: "Manage-surveys",
      private: true,
      element: <ManageSurveys />,
    },

    {
      path: adminRouteMap?.PARTICIPANTRESPONSE?.path,
      name: "Survey-analysis",
      private: true,
      element: <SurveyAnalysis />,
    },
    {
      path: adminRouteMap?.LISTOFQUESTIONS?.path,
      name: "List-of-questions",
      private: false,
      element: <ListofQuestions />,
    },
    {
      path: adminRouteMap?.PARTICIPANTASSEMENTPAGE?.path,
      name: "Participant-assesment-page",
      private: false,
      element: <AssessmentResponse />,
    },
    {
      path: adminRouteMap?.PARTICIPANTRBOEQVIEWPAGE?.path,
      name: "Participant-rboeq-page",
      private: false,
      element: <RBOEQResponse />,
    },
    {
      path: adminRouteMap?.SINGLECHARTREPORT?.path,
      name: "My-reports-single-chart",
      private: false,
      element: <SingleChartReport />,
    },
    {
      path: adminRouteMap?.SUMMARYPREVIEW?.path,
      name: "My-reports-summary-chart",
      private: false,
      element: <SummaryChartReport />,
    },
    {
      path: adminRouteMap?.DETAILEDANALYSISPREVIEW?.path,
      name: "My-reports-details-chart",
      private: false,
      element: <DetailedChartReport />,
    },
    {
      path: adminRouteMap.CREATEMYCOLOR.path,
      name: "Create-my-color",
      element: <CreateMyColor />,
    },
    {
      path: adminRouteMap?.IGREPORT?.path,
      name: "My-reports-ig-chart",
      private: false,
      element: <IgChartReport />,
    },

    {
      path: adminRouteMap?.DRILLDOWNREPORT?.path,
      name: "My-reports-drilldown-chart",
      private: false,
      element: <IgChartReport />,
    },

    {
      path: adminRouteMap?.DYNAMICFILTERREPORT?.path,
      name: "My-reports-dynamic-chart",
      private: false,
      element: <DynamicChartReport />,
    },
    {
      path: adminRouteMap?.MYPREPORTS?.path,
      name: "My-reports",
      private: true,
      element: <MyReports />,
    },
    {
      path: adminRouteMap?.ADMINMANAGEMENT?.path,
      name: "Admin-management",
      private: true,
      element: <AdminManagement />,
    },
    {
      path: adminRouteMap?.RANDOMRESPONSE?.path,
      name: "Random-response",
      private: true,
      element: <RandomResponse />,
    },
    {
      path: adminRouteMap?.COMPARSIONCHARTS?.path,
      name: "Comparsion-charts",
      private: true,
      element: <ComparsionCharts />,
    },
    {
      path: adminRouteMap?.CREATETEMPLATE?.path,
      name: "Create-template",
      private: true,
      element: <CreateTemplate />,
    },
    {
      path: adminRouteMap?.SAVEDREPORTS?.path,
      name: "Saved-reports",
      private: true,
      element: <SavedReports />,
    },
    {
      path: adminRouteMap?.MANAGEDATASET?.path,
      name: "Manage-dataset",
      private: true,
      element: <ManageDataset />,
    },
    {
      path: adminRouteMap?.REPORTGENERATOR?.path,
      name: "Report-generator",
      private: true,
      element: <ReportGenerator />,
    },
    {
      path: adminRouteMap?.ASSIGNSEND?.path,
      name: "Assign-send",
      private: true,
      element: <AssignSend />,
    },
    {
      path: adminRouteMap?.SCHEDULELOG?.path,
      name: "Schedule-log",
      private: true,
      element: <ScheduleLog />,
    },
    {
      path: adminRouteMap?.PARTICIPANTPROGRESS?.path,
      name: "Participant-progress",
      private: true,
      element: <ParticipantProgress />,
    },
    {
      path: adminRouteMap?.PROFILE?.path,
      name: "Profile",
      private: true,
      element: <Profile />,
    },
    {
      path: adminRouteMap?.ACCOUNTINFORMATION?.path,
      name: "Account-information",
      private: true,
      element: <AccountInformation />,
    },
    {
      path: adminRouteMap?.MYUSAGE?.path,
      name: "My-usage",
      private: true,
      element: <MyUsage />,
    },
    {
      path: adminRouteMap?.MANAGESURVEY?.path,
      name: "Manage-surveys",
      private: true,
      element: <ManageSurveys />,
    },
    {
      path: adminRouteMap?.CREATESURVEY?.path,
      name: "Create-survey",
      private: true,
      element: <CreateSurvey />,
    },
    {
      path: adminRouteMap?.REVIEWANDEDIT?.path,
      name: "Review-and-edit",
      private: true,
      element: <ReviewAndEdit />,
    },
    {
      path: adminRouteMap?.AUDITTRAIL?.path,
      name: "Audit-trail",
      private: true,
      element: <AuditTrail />,
    },
    {
      path: adminRouteMap?.PREVIEWSURVEYS?.path,
      name: "Preview-Surveys",
      private: false,
      element: <PreviewSurveys />,
    },
    {
      path: adminRouteMap?.CHARTING?.path,
      name: "Charting",
      private: true,
      element: <Charting />,
    },
    {
      path: adminRouteMap?.DEMOGRAPHICTRENDANALYSIS?.path,
      name: "Demographic-trend-analysis",
      private: true,
      element: <DemographicTrendAnalysis />,
    },
    {
      path: adminRouteMap?.COMPARATIVEANALYSIS?.path,
      name: "Comparative-analysis",
      private: true,
      element: <ComparativeAnalysis />,
    },
    {
      path: adminRouteMap?.CREATEDATASET?.path,
      name: "Create-dataset",
      private: true,
      element: <CreateDataset />,
    },
    {
      path: adminRouteMap?.REVIEWEDITDATASET?.path,
      name: "Review-edit-dataset",
      private: true,
      element: <ReviewEditDataset />,
    },
    {
      path: adminRouteMap?.COMPARATIVEANALYSISDATAHARMONIZATION?.path,
      name: "Comparative-analysis-data-harmonization",
      private: true,
      element: <ComparativeAnalysisDataHarmonization />,
    },
    {
      path: adminRouteMap?.DEFAULTSETTINGS?.path,
      name: "Default-settings",
      private: true,
      element: <DefaultSettings />,
    },
    {
      path: adminRouteMap?.EMAILFILTER?.path,
      name: "Email-filter",
      private: true,
      element: <EmailFilter />,
    },
    {
      path: adminRouteMap?.CHECKUNAUTHORIZED?.path,
      name: "Check-unauthorized",
      private: true,
      element: <CheckUnauthorized />,
    },
    {
      path: adminRouteMap.SAVERESOURCE.path,
      name: "Save-resource",
      private: !true,
      element: <SaveResource />,
    },
  ];
}
